System.Exception: IsTrue encountered ArgumentOutOfRangeException, expression was:

ints[150] == 49
.  ..     __
.  ..     |
\ _/|     |
 |  |     (threw ArgumentOutOfRangeException)
 |  (threw ArgumentOutOfRangeException)
 [1, 2, 3, 4, 5, ... (6 total)]


 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at lambda_method(Closure )
   at PowerAssert.PAssert.IsTrue(Expression`1 expression) in ...\PAssert.cs
   --- End of inner exception stack trace ---
   at PowerAssert.PAssert.IsTrue(Expression`1 expression) in ...\PAssert.cs
   at PowerAssertTests.Approvals.EndToEndTest.ApproveException(Expression`1 func) in ...\EndToEndTest.cs